spring:
  datasource:
    ddl-auto: create-drop
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/mochi_logs
    username: user
    password: password
    driverClassName=org: com.mysql.jdbc.Driver

logging:
  level:
    com.practical.springboot.service: INFO

server:
  port: 9002